name: reloadable_bloc
description: Extension to the Bloc library that provides route visibility callbacks
repository: https://github.com/stasgora/bloc-extensions/tree/master/reloadable_bloc
issue_tracker: https://github.com/stasgora/bloc-extensions/issues

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.0.1

  equatable: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.2
  lints: ^1.0.1
  coverage: ^1.0.3
