name: stateful_bloc

on:
  push:
    paths:
      - "stateful_bloc/**"
      - ".github/workflows/stateful_bloc.yaml"

  pull_request:
    paths:
      - "stateful_bloc/**"
      - ".github/workflows/stateful_bloc.yaml"


jobs:
  build:
    defaults:
      run:
        working-directory: stateful_bloc

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.2
      
      - name: Install Dependencies
        run: flutter packages get
      - name: Format
        run: dart format --set-exit-if-changed .
      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: Run tests
        run: dart test --coverage=coverage --test-randomize-ordering-seed random
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.0.3
